### PR TITLE
Allow recursive connections with DjangoFilterConnectionField

### PR DESCRIPTION
**Pull request by tangerilli**
You can't currently create a `DjangoFilterConnectionField` connection that references its containing node type, because the `__init__` method didn't expect the `type` to be a callable, and even if it did, the callable couldn't return anything at that time, because the type wouldn't be defined yet.  These changes move anything that's dependent on the type into properties, so as to defer access until after class initialization.

### CODE REVIEW

**Comment by nickhudkins** [comment]
@syrusakbary I have submitted a PR to @tangerilli's fork in hopes of avoiding opening another PR here, but hopefully if he accepts, we can get this conflict resolved and merged!

**Comment by austinnichols101** [comment]
Is there any workaround for this issue, or plans to update/integrate this PR?  

I'm running into this problem all over the place....

**Comment by tangerilli** [comment]
@austinnichols101 I've resolved the conflicts here

@syrusakbary is there anything you'd like to see changed here in order to get this merged?

**Comment by austinnichols101** [comment]
Thanks @tangerilli !

**Pull request merged**
