### PR TITLE
[WIP] Fixes DjangoFilterConnectionField filter slices being ignored with a custom resolver

### PR DESCRIPTION
**Pull request by NiallBrickell**
TODO:
- [ ] Fix tests

### CODE REVIEW

**Comment by NiallBrickell** [comment]
Breaks multiple filters filtering. Will find another solution.

**Comment by NiallBrickell** [comment]
@syrusakbary two tests are failing and I don't know enough about the repo to fix them: `test_should_query_connection` and `test_should_query_connectionfilter` in `graphene_django/debug/tests/test_query.py`. Looks like `COUNT` is missing from the SQL.

Would you mind taking a look?

**Comment by NiallBrickell** [comment]
Breaks .order_by in the resolver. Pushed an example broken test in 2117cb2.

**Comment by syrusakbary** [comment]
Sorry for taking so long to review, taking a look now :)

**Comment by NiallBrickell** [comment]
Thanks!

**Pull request merged**
