### PR TITLE
Move testing endpoint to settings

### LINKED ISSUE #866: This will break/lead to not working tests if your endpoint is not '/graphql'
https://github.com/graphql-python/graphene-django/blob/b66a3f347947804d0ab7d9763309e2977b5bcd5a/graphene_django/utils/testing.py#L12

### PR DESCRIPTION
**Pull request by syberen**
Fix #866

PLEASE NOTE: this will break testing for folks who have not pinned their version number, so maybe best to add to v3. I'm not sure which base branch to use for that, so please advise.

- Make default testing endpoint consistent with graphql endpoint suggested in the installation documentation (`/graphql`)
- Import testing endpoint from settings, provide default 
- Add test
- Document default testing endpoint, and how to override in settings

### CODE REVIEW

**Comment by ulgens** [comment]
> this will break testing for folks who have not pinned their version number,

I'm not sure this should be a concern of library/tool developers. If a breaking change is documented well enough, it's okay imo. I'll try to review rest of it today.

**Comment by syberen** [comment]
@ulgens Would you have time for a review?

**Review by zbyte64 — APPROVED** [review]
Seems reasonable to have this target our v3 release when it happens. :+1:

Any second opinions?

**Comment by firaskafri** [comment]
Hello @syberen , would you please resolve these conflicts so we can get it ready to be merged?

**Comment by syberen** [comment]
> Hello @syberen , would you please resolve these conflicts so we can get it ready to be merged?

Hi @firaskafri, I see you merged main already, do you still need my assistance? It might take a few days due to my schedule

**Comment by firaskafri** [comment]
> > Hello @syberen , would you please resolve these conflicts so we can get it ready to be merged?
> 
> Hi @firaskafri, I see you merged main already, do you still need my assistance? It might take a few days due to my schedule

Hello @syberen ! Yes it was a very tine conflict, but now seems that some of the tests are failing due to black formatting, would you please check when you have time?

**Review by ulgens — APPROVED** [review]

**Pull request merged**
