### PR TITLE
Adding Django filter as an installed app

### PR DESCRIPTION
**Pull request by RoySegall**
While trying to figure out how to filter results I came across the reference to the cookbook but there was missing a section that shows that we need to register the app we installed (Django-filters).

Hope this will be useful for me as for others as well.

### CODE REVIEW

**Comment by radekwlsk** [comment]
@RoySegall It may be a good idea to also mention it in the [docs on Filtering](http://docs.graphene-python.org/projects/django/en/latest/filtering/#filtering). Docs mention cookbook itself, but not everyone is going to check that out.

**Comment by RoySegall** [comment]
> but not everyone is going to check that out

Well.. I did 😁. Any way, the docs you mentioned located in [here](https://github.com/graphql-python/graphene/tree/master/docsP), right?

**Comment by radekwlsk** [comment]
> Well.. I did 😁. Any way, the docs you mentioned located in [here](https://github.com/graphql-python/graphene/tree/master/docsP), right?

https://github.com/graphql-python/graphene-django/blob/master/docs/filtering.rst

**Comment by RoySegall** [comment]
10x! I'll update it later on this week.

**Comment by RoySegall** [comment]
@jkimbo Will do, on my todo list - right after Passover. Have a great day and stay at home!

**Pull request merged**
