### PR TITLE
add request context

### PR DESCRIPTION
**Pull request by colanconnon**

### CODE REVIEW

**Comment by urbandove** [comment]
Looks great

I just wanted to note that @pizzapanther has a much larger update to the DRF serializer framework in pull request #326 which this PR should probably be merged with

Also - being that the graphene project has 2.0.1 with new supported types (specifically the Date type) - I would say its premature to bump the graphene-django version without supporting those new types (shameless plug for my pull request #335 ;) )

**Comment by colanconnon** [comment]
@urbandove I agree this should be added along with that pr. Also, the version bump was just some debugging from me, I will revert that.

**Comment by colanconnon** [comment]
@urbandove I made a pr into that branch. If we get that merged I can close this.

**Comment by syrusakbary** [comment]
Closing this PR as #326 had the same fix and is already merged into `master`

**Pull request closed without merging**
