### PR TITLE
fix(converter): wrap field with NonNull if it is required

### PR DESCRIPTION
**Pull request by helloqiu**
#536

### CODE REVIEW

**Comment by dulmandakh** [comment]
@helloqiu could you please rebase and resolve the conflict. Thank you

**Comment by helloqiu** [comment]
@dulmandakh Sure.

**Comment by jarcoal** [comment]
Any interest in reopening this PR?  The bug it fixes is still present in the codebase.

**Comment by jkimbo** [comment]
Released in [v2.11.0](https://github.com/graphql-python/graphene-django/releases/tag/v2.11.0)

**Pull request closed without merging**
