### PR TITLE
Add typed filters (v2)

### PR DESCRIPTION
**Pull request by tcleonard**
Add the ability to declare filters with an explicit GraphQL argument type.

(note that a big portion of this PR is simply to split up the filters into separate files to be more maintainable)

### CODE REVIEW

**Comment by tcleonard** [comment]
I had to cherry pick the PR #1136 (which should be ready to be merged) as it partially depends on it.

**Comment by ulgens** [comment]
@tcleonard #1136 is merged :tada:

**Review by zbyte64 — APPROVED** [review]
:+1:

**Comment by ulgens** [comment]
@tcleonard Is there any chance for instead of merging v2 into the this branch, just rebase this branch onto v2?

**Comment by tcleonard** [comment]
I have rebased and squashed commits

**Pull request merged**
