### PR TITLE
Upgrade github actions versions, default python and dev dependencies

### PR DESCRIPTION
**Pull request by firaskafri**
- [x] Use Python 3.10 in deploy.yml
- [x] Use Python 3.10 in lint.yml
- [x] Update setup-python and checkout versions
- [x] Update .pre-commit-config.yaml 
- [x] Match dev dependencies versions with workflows 
- [x] `make format` for examples files and migrations to follow the new black version
- [x] Upgrade pytest version

### CODE REVIEW

**Review by kiendang — COMMENTED** [review]
We should update the GH action from `pypa/gh-action-pypi-publish@v1.1.0` (it's been 3 years) to `pypa/gh-action-pypi-publish@release/v1` (the latest `v1`) as well. See https://github.com/pypa/gh-action-pypi-publish.

Also probably use `3.10` in `lint.yml` as well just for consistency.

**Comment by firaskafri** [comment]
@kiendang You are right! Updated the PR and I am on the reset of the points!

**Comment by kiendang** [comment]
May as well update the other actions to latest versions too, `actions/setup-python` and `actions/checkout`.

**Comment by kiendang** [comment]
Thanks for doing this. I've planned to do this as well since I did the exact same thing for graphql-server recently, but was waiting for #1365 to ber merged.

**Comment by firaskafri** [comment]
@kiendang thank you for reviewing this with me!
Linting is failing though, any idea why could this be happening?

**Comment by firaskafri** [comment]
@kiendang so now we have a black formatting issue, what do you suggest?

**Review by mahdyhamad — APPROVED** [review]

**Review by kiendang — APPROVED** [review]

**Pull request merged**
