### PR TITLE
Cleaned up unused imports and variables.

### PR DESCRIPTION
**Pull request by jackton1**

### CODE REVIEW

**Comment by ulgens** [comment]
@jackton1 If you can remove merge commit from the branch, it seems good to go.

**Comment by jackton1** [comment]
> @jackton1 If you can remove merge commit from the branch, it seems good to go.

Done.

**Review by ulgens — APPROVED** [review]

**Comment by ulgens** [comment]
@zbyte64 @tcleonard Any comments to add?

**Review by tcleonard — APPROVED** [review]

**Comment by ulgens** [comment]
Two approvals and i'm merging this in.

**Pull request merged**
