### PR TITLE
Backport Django 4.1 compatibility fixes to v2

### PR DESCRIPTION
**Pull request by santiagoaguiar**
This backports https://github.com/graphql-python/graphene-django/pull/1281/commits/e584d5ef5d56cd3f1fdaaca9d8897f04326ed471 to v2 to be used with Django 4.1.

Hoping we can get this to a 2.16 release 🙏 .

### CODE REVIEW

**Review by sjdemartini — APPROVED** [review]
I'm not sure the status of graphene-django v2, but the changes here LGTM

**Review by firaskafri — APPROVED** [review]

**Comment by santiagoaguiar** [comment]
Ay thoughts on why the build could be failing? Doesn't seem to be related to my changes I think?

**Review by kiendang — APPROVED** [review]

**Comment by kiendang** [comment]
@santiagoaguiar just need backporting a bunch of test and CI updates as well. all settled now.

**Comment by firaskafri** [comment]
@santiagoaguiar Just released v2.16.0 :)

**Pull request merged**
