### PR TITLE
Not require explicitly set `ordering` in `DjangoConnectionField`

### PR DESCRIPTION
**Pull request by kiendang**
I'm working on fixing #1516, probably by setting `ordering = ["pk"]` by default in `DjangoConnectionField` `class Meta`. 

However I don't find any reference of `ordering` in both this or Graphene's code base. Does anyone have any idea? Or is setting `ordering` actually not doing anything? @sjdemartini @tcleonard

### CODE REVIEW

**Comment by gsvr** [comment]
@kiendang It looks like you're getting stuck at the same place I did - there doesn't seem to be an easy way to define ordering in a Meta class somewhere. The only ordering method I could find in the docs was using an [OrderingFilter](https://docs.graphene-python.org/projects/django/en/latest/filtering/#ordering), but setting a default with that doesn't look easily viable. I would suggest opening another feature issue to implement default ordering so this PR can be wrapped up :)

**Comment by kiendang** [comment]
@gsvr my problem is that I don't know if setting

```py
class Meta
    ordering = ["pk"]
```

actually does anything because I can't seem to find any code that references `ordering` in this or Graphene code base.

If that is the case, we should just revert #1518.

In case that `ordering` actually works, setting a default `ordering` is doable, but even in this case I'm fine with reverting #1518 first then implementing that later.

**Comment by gsvr** [comment]
@kiendang Yeah, I also searched around, and I don't think setting ordering in class Meta actually does anything. I couldn't find any usage of that in the docs or the code.

**Review by sjdemartini — APPROVED** [review]
lgtm to revert, thanks for handling this!

**Review by firaskafri — APPROVED** [review]

**Pull request merged**
