### PR TITLE
Register multiple choice field as list

### PR DESCRIPTION
**Pull request by ulgens**
`MultipleChoiceField` was registered as text input when it should be list.

### CODE REVIEW

**Comment by ulgens** [comment]
@jkimbo Hey :wave: Should i create another PR for v3?

**Comment by jkimbo** [comment]
@ulgens the way I've been handling v3 for Graphene-Django is to merge the master branch into v3 every so often. So there is no need to create a PR specifically against the v3 branch.

**Comment by ulgens** [comment]
@zbyte64 Any luck here? :slightly_smiling_face:

**Review by zbyte64 — APPROVED** [review]
Looks good :+1:

**Comment by ulgens** [comment]
@zbyte64 Anything missing for a merge? :sli

**Comment by SantiagoAndre** [comment]
thanks is what i was looking for.
I don't know much about the handling of integrations, are these changes already in the latest version of the framework?
I need this update
thanks

**Comment by ulgens** [comment]
@SantiagoAndre This is merged to master but no new release is out yet. You can use it if you install the package over git repository.

**Comment by SantiagoAndre** [comment]
I found another problem, when I create DjangoFormMutation, and a form input field is a ModelMultipleChoiseFIeld, the response type of Mutation: "Payload", define this field as a list of IDS, the correct thing would be a list field of the model "Subject ", to be able to use the advantages that graphql brings when consuming the api.
```python
class MyForm(forms.Form):
        subject = forms.ModelMultipleChoiceField(label = _("subjects"),
    queryset=Subject.objects.all())
class CreateMonitor(DjangoFormMutation):
    class Meta:
       form_class = RegistryMonitorForm    
```
### Mutation
image

### Automatic reponse type of model field

image

#### How to consume this  Mutation
```graphql
  createMonitor(input: {
         subject: ["U3ViamVjdE5vZGU6MQ==","U3ViamVjdE5vZGU6Mg=="]
    }) {
    subject
   }
  -------------- RESULT --------------------------
{
  "data": {
    "createMonitor": {
      "subject": [
        "1",
        "2"
      ],
      "errors": null
    }
  }
}
```
### Esperated type

image
image

#### How to consume this  Mutation
```graphql
  createMonitor(input: {
         subject: ["U3ViamVjdE5vZGU6MQ==","U3ViamVjdE5vZGU6Mg=="]
    }) {
    subject{
         edges{
             node{
                   id
                  name
             }
        }
   }
}
   }
  -------------- RESULT --------------------------
{
  "data": {
    "createMonitor": {
     "subject": {
          "edges": [
            {
              "node": {
                "name": "subject name",
                "id": "U3ViamVjdE5vZGU6MQ=="
              }
            }
          ]
        },
      "errors": null
    }
  }
}


This change sounds great, could be add to next release

**Pull request merged**
