### PR TITLE
Ensure code example is fully functional

### PR DESCRIPTION
**Pull request by whirish**
Simple change, it took me a while to figure out why the documentation's code was throwing an AssertionError :)

### CODE REVIEW

**Comment by wsantos** [comment]
Are you sure? I'm using `Object` without a problem.

**Comment by whirish** [comment]
I'm pretty sure it's tied to this, it was a fresh install on my end and everything. You're on the latest version and py3?

**Comment by zbyte64** [comment]
I think having `Query` inherit `ObjectType` is proper usage.

**Comment by jkimbo** [comment]
Thanks @whirish !

**Pull request merged**
