### PR TITLE
Fix reverse o2o relation resolution

### PR DESCRIPTION
**Pull request by mvanlonden**
Fixes https://github.com/graphql-python/graphene-django/issues/662
Supersedes https://github.com/graphql-python/graphene-django/pull/663

@robertpro used your fix and added some tests so we won't see this regression again

### CODE REVIEW

**Comment by robertpro** [comment]
@mvanlonden Thanks!, I am still learning graphene, next time I will add tests!

**Comment by mvanlonden** [comment]
Added tests to @robertpro 's PR

**Comment by robertpro** [comment]
@mvanlonden you closed this PR instead of merge?

**Comment by mvanlonden** [comment]
Yes I wanted to keep your contribution so I just added my tests to the PR you started @robertpro

**Comment by robertpro** [comment]
Nice, thanks again @mvanlonden

**Pull request closed without merging**
