### PR TITLE
Fix error of multiple inputs with the same type. When using same seri…

### LINKED ISSUE #478: SerializerMutation creates excess types for fields with same serializer class
I use ``SerializerMutation`` to create/update objects:

```python
from graphene_django.rest_framework.mutation import SerializerMutation

class ShipmentMutation(SerializerMutation):
    class Meta:
        serializer_class = ShipmentSerializer
```

Here is ``ShipmentSerializer``:

```python
from rest_framework import serializers

from logistics.models import City
from logistics.serializers import CitySerializer

from .models import Shipment


class ShipmentSerializer(serializers.ModelSerializer):
    owner = serializers.PrimaryKeyRelatedField(read_only=True)
    origin = CitySerializer(read_only=True)
    destination = CitySerializer(read_only=True)

    class Meta:
        model = Shipment
        exclude = ('created_at', 'updated_at', )
```

...and ``CitySerializer``:

```python
class CitySerializer(serializers.ModelSerializer):
    class Meta:
        model = City
        fields = ('id', 'name', )
        read_only_fields = ('id', 'name', )
```

So there is ttwo similar fields serialized by ``CitySerializer``: ``origin`` and ``destination`` and while creating appropriate types for it raises an error:

```python
AssertionError: Found different types with the same name in the schema: CitySerializerInput, CitySerializerInput.
```

<details><summary>Full trace</summary>

```python
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb41bb8b620>
Traceback (most recent call last):
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 55, in inner_run
    self.check(display_num_errors=True)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/someusernamehere/donnyyy/Workspace/m100/m100-backend/m100/urls.py", line 21, in <module>
    from main.views import graphql_view
  File "/someusernamehere/donnyyy/Workspace/m100/m100-backend/main/views.py", line 100, in <module>
    '.')[:-1])), settings.GRAPHENE['SCHEMA'].split('.')[-1])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/someusernamehere/donnyyy/Workspace/m100/m100-backend/main/schema.py", line 75, in <module>
    + car_types
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/schema.py", line 62, in __init__
    self.build_typemap()
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/schema.py", line 126, in build_typemap
    initial_types, auto_camelcase=self.auto_camelcase, schema=self
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 80, in __init__
    super(TypeMap, self).__init__(types)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/typemap.py", line 28,in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/typemap.py", line 106, in reducer
    field_map = type.fields
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/definition.py", line 221, in fields
    return define_field_map(self, self._fields)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/definition.py", line 235, in define_field_map
    field_map = field_map()
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 286, in construct_fields_for_type
    map = self.reducer(map, arg.type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 93, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/typemap.py", line 106, in reducer
    field_map = type.fields
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/definition.py", line 655, in fields
    return self._define_field_map()
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphql/type/definition.py", line 660, in _define_field_map
    fields = self._fields()
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 274, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/someusernamehere/.local/lib/python3.6/site-packages/graphene/types/typemap.py", line 99, in graphene_reducer
    ).format(_type.graphene_type, type)
AssertionError: Found different types with the same name in the schema: CitySerializerInput, CitySerializerInput.
```

</details>

### PR DESCRIPTION
**Pull request by Hispar**
…alizer.

Fix #478

### CODE REVIEW

**Comment by danpalmer** [comment]
I'm afraid I don't have any experience with Django Rest Framework, so I'm going to opt-out of reviewing this one.

**Comment by jkimbo** [comment]
I don't have any experience with Django Rest Framework either unfortunately.

**Comment by Hispar** [comment]
> Will this change require existing code bases to update their client? If I understand correctly the input type label will change.

I'm not sure, the types are generated every time the schema is created. I have been using this fix several months without problems.

**Comment by Hispar** [comment]
> We ran into this problem. The pull request solves the problem, but is it necessary to create 2 Input types? would't be more appropriate to reuse the first one that gets created? After all if its the same Serializer, should be also the same serializer input type right?

The correct way should be to reuse the first type as you are saying. But when I encountered this problem I didn't find the way to do it, so I implemented this workaround meanwhile. I haven't had time to look for a better solution.

**Comment by dani0805** [comment]
Yes, I hear you ... we commented the assertion :-)

something like this?  (Did not test it as I don't have the project setup)

```
def convert_serializer_to_input_type(serializer_class):
    cachedType = convert_serializer_to_input_type.cache.get(serializer_class.__name__, None)
    if cachedType:
        return cachedType
    serializer = serializer_class()

    items = {
        name: convert_serializer_field(field)
        for name, field in serializer.fields.items()
    }
    retType = type(
        "{}Input".format(serializer.__class__.__name__),
        (graphene.InputObjectType,),
        items,
    )
    convert_serializer_to_input_type.cache[serializer_class.__name__] = retType
    return retType
convert_serializer_to_input_type.cache = {}
```

**Comment by Hispar** [comment]
> Yes, I hear you ... we commented the assertion :-)
> 
> something like this? (Did not test it as I don't have the project setup)
> 
> ```
> def convert_serializer_to_input_type(serializer_class):
>     cachedType = convert_serializer_to_input_type.cache.get(serializer_class.__name__, None)
>     if cachedType:
>         return cachedType
>     serializer = serializer_class()
> 
>     items = {
>         name: convert_serializer_field(field)
>         for name, field in serializer.fields.items()
>     }
>     retType = type(
>         "{}Input".format(serializer.__class__.__name__),
>         (graphene.InputObjectType,),
>         items,
>     )
>     convert_serializer_to_input_type.cache[serializer_class.__name__] = retType
>     return retType
> convert_serializer_to_input_type.cache = {}
> ```

It could work, at this moment I do not have the project configured to test it, but as soon as I can I will see if it works and I will update the PR accordingly.

Thanks!

**Comment by Hispar** [comment]
@dani0805 I have updated the PR with your solution, I haven't tested it in our projects yet, but the test of the schema works.

**Comment by kimbriancanavan** [comment]
This would solve headaches for us. Let's get this merged :+1:

**Comment by Shehab-Muhammad** [comment]
why no one reviews and merges this, please merge this ASAP

**Comment by phalt** [comment]
Hey @Shehab-Muhammad please appreciate that this project is worked on my volunteers in their spare time!

**Comment by Shehab-Muhammad** [comment]
@phalt I appreciate your work, of course. thank you

**Pull request merged**
