### PR TITLE
refactor how _convert_choices_to_enum is calculated.

### PR DESCRIPTION
**Pull request by a-c-sreedhar-reddy**

### CODE REVIEW

**Comment by jkimbo** [comment]
@a-c-sreedhar-reddy is this PR fixing a bug? If it is can you create a test for it?

**Comment by a-c-sreedhar-reddy** [comment]
@jkimbo It is not a fix for a bug. It makes code more readable.

**Comment by jkimbo** [comment]
I don't agree, I actually think the change makes the code less readable. Generally splitting out the logic into multiple steps is more readable than using ternarys.

Sorry I'm not going to accept this change. I'm happy to accept changes that make the code easier to reason about but I don't think this change does that.

**Comment by jkimbo** [comment]
Also I don't want to discourage you from contributing @a-c-sreedhar-reddy , I just don't think this change is a good one.

**Pull request closed without merging**
