### PR TITLE
WIP: Graphene 3 (continuation)

### PR DESCRIPTION
**Pull request by ganwell**
Continuation of #774

* Adding fixes needed to run projectcaluma/caluma/issues/814 unittests

* Still very much WIP

Related Issues:

- [x] graphql-python/graphene/pull/1111

My workspace: https://github.com/ganwell/gwork

### CODE REVIEW

**Comment by ganwell** [comment]
Rebasing was a mistake, it introduces to much uncertainty.

**Comment by jkimbo** [comment]
This looks really good @ganwell . Is the outstanding issue on Graphene the only thing blocking this?

**Comment by ulgens** [comment]
Any progress on this?

**Comment by ganwell** [comment]
@jkimbo Last month I started to run graphen-django v3 against our test-suite (https://github.com/projectcaluma/caluma), but I got distracted by other projects. I was able to reduce errors from 500 of 600 to about 150 of 600. I assume there are still bugs in the graphql*/graphene* projects, some are in caluma itself of course. I hope I can resume the work in February.

**Comment by jkimbo** [comment]
@ganwell thanks for the update. FYI I've merged https://github.com/graphql-python/graphene/pull/1111 so you should be unblocked there.

**Comment by ganwell** [comment]
I will try to switch to #905 and continue my integration test

**Comment by ganwell** [comment]
Closing because of v3 branch

**Pull request closed without merging**
