### PR TITLE
Fix select_related with filtering

### PR DESCRIPTION
**Pull request by camd**
I must admit, I don't totally see the need for this union between the ``default_queryset`` and ``queryset`` but through experimentation, I have found that if the order of the union is reversed, it will preserve the ``select_related`` and ``prefetch_related``.  It has the same effect of finding the union of records returned.  The list is identical.

So I hope this change doesn't break something I'm not aware of.  :)

This is an attempt to fix https://github.com/graphql-python/graphene-django/issues/179

### CODE REVIEW

**Comment by spockNinja** [comment]
@syrusakbary Same fix as #194, just specific to filter fields. Looks fine to me.

**Comment by jancespivo** [comment]
Hi, IMO this code violates DRY principle and should be refactorized. The DjangoFilterConnectionField is inherited from DjangoConnectionField where the code is ok (in classmethod merge_queryset). I agree with this fix (it's the same fix as mine in duplicate #272 ) but I think it is definitely not a good final solution.

**Comment by camd** [comment]
Thanks for accepting the fix!  I'm not able to merge it, so I'll leave that to the project collaborators.  Thanks everyone.  :)

**Comment by syrusakbary** [comment]
I agree with @jancespivo that the code needs to be refactored, but we can do it in a separate PR.

The change looks good, but I think before merging the PR should include tests ensuring that the issue is not repeated in future releases.

**Comment by spockNinja** [comment]
7a110ab should address everyone's concerns. Using `super` to use `DjangoConnectionField`'s default implementation. Since the base class's implementation was tested in #194 then it is tested here.

Tests are failing, but it's unrelated. I'm looking into those failures in a separate PR.

**Comment by spockNinja** [comment]
Now that the failing test in master is fixed, this PR is ✅.

@syrusakbary Ready for merge, and I can close several duplicate issues/PRs for this bug.

**Comment by camd** [comment]
Thanks for the merge!  :)

**Comment by urbandove** [comment]
There's an issue with this merge - if a class is subclassing `DjangoFilterConnectionField` and a queryset is returned from `resolve_schema_field` the `super(cls,cls)` refers back to `DjangoFilterConnectionField` and has an endless loop.

**Pull request merged**
