### PR TITLE
fix: declaration of required variable in filters v2

### PR DESCRIPTION
**Pull request by tcleonard**
This is to fix the problem you reported @ulgens

### CODE REVIEW

**Comment by ulgens** [comment]
Is there any chance we can add test for this too? I didn't understand how tests are didn't fail before.

**Comment by tcleonard** [comment]
yep I can add a test for it, good point. (it's when you don't use any automatic filters and only custom ones)

**Comment by tcleonard** [comment]
There is a test failing which I have no idea what it is about... it doesn't seem linked to what I have changed I can't reproduce this failure locally... any idea?

**Comment by zbyte64** [comment]
I'll play with it this weekend, looks like names is an empty string when it attempts to generate an enum for the file path field.

**Comment by zbyte64** [comment]
Can hack around it by modifying: graphene_django/converter.py: convert_choices_to_named_enum_with_descriptions
```
    if not len(named_choices):
        named_choices = set()
    return Enum(name, named_choices, type=EnumWithDescriptionsType)
```

Python 2.7 doesn't handle enums with lists or tuples with zero entries - but works okay if we pass a set or generator. The file path field in the test has no child folders, therefor we get an empty set of choices.

**Review by ulgens — APPROVED** [review]

**Review by zbyte64 — APPROVED** [review]
:+1:

**Pull request merged**
