### PR TITLE
Added tox.ini and improved travis.yml

### PR DESCRIPTION
**Pull request by ZuluPro**
I added a tox file to ease test across Python & Django versions.
I also improved the travis file to use the tox configuration.

### CODE REVIEW

**Comment by ZuluPro** [comment]
@sciyoshi  Any news ?

**Comment by sciyoshi** [comment]
Looks fine to me, but I don't have commit access. Please ask @syrusakbary or @jm2242 to review + merge.

**Comment by jm2242** [comment]
I'm happy to take a look but I'm not sure I'm involved in the project enough to have a say!

**Comment by firaskafri** [comment]
@ZuluPro Interested to update this pull request?

**Comment by ZuluPro** [comment]
Hello @firaskafri @zbyte64 

I updated my PR, exclude <Django 1.10

**Comment by phalt** [comment]
I'd like to tidy up some of the PRs, so if we still want to work on this let me know or I will close this in 1 week.

**Comment by dulmandakh** [comment]
LGTM. @ZuluPro could you please remove 1.10 and 2.0 as these are not supported anymore.

**Comment by phalt** [comment]
Please resolve conflicts

**Comment by ZuluPro** [comment]
@phalt @zbyte64 : Rebased !

Note:
Django master's tests are failing due to a `six` import: 
```
File "/home/travis/build/graphql-python/graphene-django/graphene_django/settings.py", line 18, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/travis/build/graphql-python/graphene-django/.tox/py3.7-djangomaster/lib/python3.7/site-packages/django/utils/__init__.py)```

**Comment by dulmandakh** [comment]
@ZuluPro @phalt I think we need to add **six** as dependency and import it directly, rather than from Django.

**Pull request merged**
