### PR TITLE
Section added `GraphQL testing clients`

### PR DESCRIPTION
**Pull request by Nishchit14**
Section added `GraphQL testing clients` in README.md

### CODE REVIEW

**Comment by ulgens** [comment]
@jkimbo ping

**Comment by ganwell** [comment]
@jkimbo rebased and reviewed.

**Comment by ulgens** [comment]
@zbyte64 @jkimbo @ganwell Anyone to merge?

**Comment by ganwell** [comment]
@ulgens Unfortunately I cannot merge, as it seems.

> You’re not authorized to merge this pull request.

**Pull request merged**
