### PR TITLE
Fix graphene 1.3 annotation bug

### LINKED ISSUE #173: graphene 1.3 annotation bug
There seems to be a bug with graphene == 1.3

I have a model that I annotate a field "total_rent"
I think graphene is stripping it away somehow

I get this exception ```Cannot resolve keyword 'total_rent' into field. Choices are ... ```

When reverting back to graphene == 1.2.1 the error goes away.
I wish I could provide a more in depth report but my deadlines are to much at the moment

### PR DESCRIPTION
**Pull request by dvdmgl**
Fixes #173

### CODE REVIEW

**Comment by crucialfelix** [comment]
Thanks for the fix.  What is in default_query_set that it should always be merged with the query_set that we supply ? It seems to me that I supply a query_set then it should be used as is. Merging with default_query_set seems dangerous.

**Comment by jole78** [comment]
is this fix released on PyPI??

**Comment by crucialfelix** [comment]
I don't think so

**Comment by dleitee** [comment]
Why is it not o PyPi?

**Pull request merged**
