### PR TITLE
Adding introduction tutorial using "plain" Graphene

### PR DESCRIPTION
**Pull request by RadoRado**
Based on discussions here: https://github.com/graphql-python/graphene-django/issues/106

Things to be done:

1) Better naming for titles of the tutorial pages
2) Adding some examples for error handling?
3) Adding `Summary` section in the plain tutorial
4) Adding additional explanations to the relay tutorial

:beers:

### CODE REVIEW

**Comment by syrusakbary** [comment]
Great work here! Let me know when is ready to review :)

**Comment by RadoRado** [comment]
@syrusakbary Sure. The major question is to add some clarity in the relay tutorial. I will try to do it but I'm still not sure how everything fits together there :+1: 

For now - do you think the plain tutorial is covering enough?

:beers:

**Comment by RadoRado** [comment]
@syrusakbary Few things that you can take a look at:

1) Added `cookbook-plain` in the examples, which is a remake of the original `cookbook` project. Cleaned few `flake8` errors, can do the same for `cookbook`
2) Check the structure of `tutorial-plain.rst`. What do you think of it? I can do the same structure for `tutorial-relay.rst` which will clean some of the text and leave place for more relay stuff.
3) Can you check the resolvers that are looking by id. I am currently returning `None`. Is there a spec / best practices for handling such errors in GraphQL?

Thanks! :beers:

**Comment by syrusakbary** [comment]
Will take a closer look to this PR this weekend!
Thanks for the great work!! 💪

**Comment by syrusakbary** [comment]
@RadoRado Everything looks good!

✅ cookbook-plain examples
✅ The tutorial plain example. It might be worth to point the `tutorial-plain` that is recommended to follow the Relay tutorial in case to have paginated relations automatically :)
✅ Returning `None` is a perfectly safe practice whenever something is not found, so nothing to worry here.

Other than the small nits, once the merge conflicts are solved I would love to merge this PR.

**Comment by RadoRado** [comment]
@syrusakbary Thanks! Will fix the things from the comments.

One thing that I wonder - do you want me to change the relay tutorial to follow the same structure as the plain one? Especially the Django setup can be more compact.

Cheers :beers:

**Comment by syrusakbary** [comment]
> One thing that I wonder - do you want me to change the relay tutorial to follow the same structure as the plain one? Especially the Django setup can be more compact.

Would be great if you wanna tackle it in this PR!

**Comment by RadoRado** [comment]
@syrusakbary Great. Will get to work and push some more commits.

**Comment by RadoRado** [comment]
@syrusakbary I've done the restructuring of the relay tutorial + added some external links.

The interesting part is that I cannot get that merge conflict in my fork. Everything merges correctly. The problem may be that I have renamed `tutorial.rst` to `tutorial-relay.rst` and added `tutorial-plain.rst`.

Any idea how to resolve this?

Cheers :beers:

**Comment by syrusakbary** [comment]
Done! 😉

**Pull request merged**
