### PR TITLE
WIP: Graphene 3

### PR DESCRIPTION
**Pull request by ktosiek**
Related to #705. I've started working on porting graphene-django to Graphene 3.
For now I'm just fixing tests from the top, but I'm sharing this in case anyone else is intrested.

### CODE REVIEW

**Comment by jkimbo** [comment]
This is great! Thanks so much @ktosiek . Is there anything outstanding left to do?

**Comment by ktosiek** [comment]
1. This is blocked by https://github.com/graphql-python/graphql-core-next/issues/61 (which I hope to finish soon).
2. This was never used in an application (except for the cookbook example), so it might be incomplete.
3. I haven't looked through documentation yet, it might still reference Python 2 or Django Filters 1.x

**Comment by ktosiek** [comment]
1. https://github.com/graphql-python/graphql-core-next/issues/61 is done, and I've updated this PR accordingly.
2. Still no real-world testing, and I'm not sure when I'll be able to do that (the only app I could try this on uses django-graphql-optimizer heavily).
3. I've looked through the docs, (but not very thoroughly, to be honest), and fixed 2 references to Django <1.11.

**Comment by ganwell** [comment]
@ktosiek I am going to run this against few of our projects.

**Comment by BfutureP** [comment]
Anyone please review it ASAP. It will be helpful for my project... upgrqaded to Django v3 with Graphene v3 and Graphene-Django v3. thanks. @ #812

**Comment by ulgens** [comment]
@ktosiek Is this still WIP?

**Comment by ktosiek** [comment]
@ulgens I'm not working on this at the moment, but I see @ganwell has taken over in a separate PR: #812.

**Comment by ganwell** [comment]
@jkimbo I fear that tox was not working on #904 and #905. I want to start over and incrementally (a PR and review per commit) merge #774. I also have some issues with flaky tests on master and I want to fix that first in master: Introducing random test order.

**Comment by ulgens** [comment]
@jkimbo Just give me some time to fix those test config. I'm saying that everything is already in place :slightly_smiling_face: No need for any additional work here.

**Comment by jkimbo** [comment]
Closing this since https://github.com/graphql-python/graphene-django/pull/951 has been merged into the v3 branch

**Pull request closed without merging**
