### PR TITLE
Add support for write_only fields in SerializerMutation

### PR DESCRIPTION
**Pull request by kamilkijak**
Closes: #487

### CODE REVIEW

**Comment by kamilkijak** [comment]
@syrusakbary @patrick91 I would appreciate your feedback guys 🙂

**Comment by danpalmer** [comment]
I'm afraid I don't have any experience with Django Rest Framework, so I'm going to opt-out of reviewing this one.

**Comment by jkimbo** [comment]
Don't have any experience with Django Rest Framework either

**Comment by firaskafri** [comment]
Nice! Approved from my side.

**Comment by jkimbo** [comment]
Merged. Thanks @kamilkijak

**Comment by Shehab-Muhammad** [comment]
Could you release this update to the latest version on pip?

**Comment by banxi1988** [comment]
Hi, I feel we also need to exclude the read_only field in the InputType.

```py
        if is_not_in_only or is_excluded:
            continue
        if is_input and field.read_only:
            continue
```

**Comment by jkimbo** [comment]
@Shehab-Muhammad the latest version has been released as v2.4.0

@banxi1988 please make a PR if there are still features that need implementing.

**Pull request merged**
