### PR TITLE
graphiql version upgrade close #572

### LINKED ISSUE #572: GraphiQL to version v0.11.11?
Proposal to move to GraphiQL v0.11.11 to solve a markdown issue in the documentation:
cfr. https://github.com/graphql/graphiql/issues/575

Scanning over the code, the main difference between v0.11.10 and v0.11.11 is a switch from 'marked' to 'markdown-it' for rendering the documentation.

Affected lines:
https://github.com/graphql-python/graphene-django/blob/f76f38ef30b88d921df243b09c4970528b1a4007/graphene_django/views.py#L54

### PR DESCRIPTION
**Pull request by Zorig**

### CODE REVIEW

**Comment by phalt** [comment]
@Zorig have you tested that this works? We don't need to do anything else?

**Comment by Zorig** [comment]
@phalt i think so, the template file is getting `graphiql` version from view then fetch from CDN.

**Comment by phalt** [comment]
@Zorig if you've tested it locally then I'll go ahead and merge it :)

**Comment by Zorig** [comment]
yup, go ahead.

**Pull request merged**
